@Metadata.layer: #CORE
annotate entity ZC_ITENS_OV
    with 
{
    
  @UI.lineItem: [{ position: 10 }]
  SalesOrder;
  @UI.lineItem: [{ position: 20 }]
  SalesOrderItem;
  @UI.lineItem: [{ position: 30 }]
  SalesOrderItemCategory;
  @UI.lineItem: [{ position: 40 }]
  SalesOrderItemType;
  @UI.lineItem: [{ position: 50 }]
  IsReturnsItem;
  @UI.lineItem: [{ position: 60 }]
  CreatedByUser;
  @UI.lineItem: [{ position: 70 }]
  CreationDate;
  @UI.lineItem: [{ position: 80 }]
  CreationTime;
  @UI.lineItem: [{ position: 90 }]
  LastChangeDate;
  @UI.lineItem: [{ position: 100 }]
  Division;
  @UI.lineItem: [{ position: 110 }]
  Material;
  @UI.lineItem: [{ position: 120 }]
  Batch;
  @UI.lineItem: [{ position: 130 }]
  Plant;
} 